labelPRBasedOnFilePath:
  need review:
    - "CNPack/**"

  kubejs:
    - "CNPack/kubejs/**"

  resource:
    - "CNPack/kubejs/assets/**"
    - "CNPack/config/fancymenu/**"

  ftbquest:
    - "CNPack/config/ftbquests/**"
    - "CNPack/kubejs/assets/ftbquests**"

labelerFlags:
    labelOnPRUpdates: true  

firstPRWelcomeComment: >
  - 请确定此 Pull Request 的目标分支是否正确
  - 请确定此 Pull Request 的状态，若未完成，请设置为 Draft
  - 劣质的机器翻译请不要轻易提交，但是机翻润色是允许的
  - 请耐心等待审核，审核完成后请及时前来处理
