name: Manual Release

on:
  # 手动触发事件
  workflow_dispatch:
    inputs:
      release_tag:
        description: 'Release Tag'
      commit:
        description: 'Full SHA of Special Commit'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Source
      uses: actions/checkout@v3

    - name: Setup Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Clone Official Modpack Repo (With Special Commit)
      run: |
        git clone https://github.com/Laskyyy/Create-Astral.git
        cd Create-Astral && git reset --hard ${{ github.event.inputs.commit }} && cd ..

    - name: Make Release
      run: python make_release.py

    - name: Create GitHub release
      uses: marvinpinto/action-automatic-releases@latest
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        automatic_release_tag: ${{ github.event.inputs.release_tag }}
        title: ${{ github.event.inputs.release_tag }}
        prerelease: false
        files: |
          release/release.zip

