name: Packer
on:
    workflow_dispatch: 
    schedule:
        - cron: 
            0 0 * * *
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Get current date
        id: date
        run: echo "::set-output name=date::$(date +'%Y-%m-%d')"
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 机械动力星辰汉化补丁${{ steps.date.outputs.date }}.zip
          path: ./CNPack
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "机械动力星辰汉化补丁${{ steps.date.outputs.date }}.zip"
          tag: "Realease-${{ steps.date.outputs.date }}"