name: Packer
on:
    workflow_dispatch: 
    schedule:
        - cron: 
            0 0 * * *
jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.3
      - name: Get current date
        id: date
        run: echo “DATE=$(date +‘%Y-%m-%d’)” >> $GITHUB_ENV
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: 机械动力星辰汉化补丁 $(date +‘%Y-%m-%d’).zip
          path: ./CNPack
      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "机械动力星辰汉化补丁 $(date +‘%Y-%m-%d’).zip"
          tag: "机械动力星辰汉化补丁-$(date +‘%Y-%m-%d’)"